version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
  redis_container:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'


volumes:
  mongodb_data_container: